# Hypothesis Testing with the $t$-test

## The Lady Tasting Tea

Our story of statistical hypothesis testing begins with Ron Fischer and Muriel Bristol who were colleagues at a British research station right after World War I. The story begins with a meeting where Ron offered Muriel a cup tea. The results were surprising and changed the course of scientific research forever.

[The Wikipedia article has details.](https://en.wikipedia.org/wiki/Lady_tasting_tea)

## Examples

Let's first load some data which serve for examples of each type of $t$-test.

In [3]:
pers <-read.csv('https://faculty.ung.edu/rsinn/data/personality.csv')
births <-read.csv('https://faculty.ung.edu/rsinn/data/baby.csv')

In [4]:
head(p,5)
head(births,5)

  Age Yr Sex G21 Corps Res Greek VarsAth Honor GPA  ... Perf OCD Play Extro
1 21  2  M   Y   Y     1   N     N       N     3.23 ... 105  10  142   8
2 20  3  F   N   N     2   Y     N       Y     3.95 ... 105   3  172  16
3 22  3  M   Y   N     2   N     N       N     3.06 ...  73   1  134  15
4 27  3  F   Y   N     3   N     N       N     2.84 ...  90   9  160  16
5 24  3  M   Y   N     2   N     N       N     2.39 ...  95   5  166  14
  Narc HSAF HSSE HSAG HSSD PHS
1 11   41   40   26   27   SE
2 11   46   52   26   33   SE
3 11   48   42   44   29   AG
4 10   51   51   23   19   SE
5 10   56   46   27   20   AF

  Birth.Weight Gestational.Days Maternal.Age Maternal.Height
1 120          284              27           62
2 113          282              33           64
3 128          279              28           64
4 108          282              23           67
5 136          286              25           62
  Maternal.Pregnancy.Weight Maternal.Smoker
1 100                       False
2 135                       False
3 115                       True
4 125                       True
5  93                       False

### Example 1

**Research Question.** Do UNG students, on average, get less than 7 hours of sleep per night?

**Hypothesis.** With correct statistical notation, we have:

$$\begin{align*}H_0 &: \mu = 7 \\ H_a &: \mu < 7\end{align*}$$

## Example 2a

**Research Question.** In the births table, do babies born to non-smoking moms weigh more than babies born to smoking moms?

**Hypothesis.** The setup here is as follows:

$$\begin{align}H_0 : \mu_\text{smoke} &= \mu_\text{non} \\H_a :  \mu_\text{smoke} &> \mu_\text{non}\end{align}$$

### Example 2b

**Research Question.** At UNG, do senior students drink more caffeine per day than freshmen?

**Hypothesis.** The setup here is as follows:

$$\begin{align}H_0 : \mu_{sr} &= \mu_{fr} \\H_a :  \mu_{sr} &> \mu_{fr}\end{align}$$

### Example 3

**Research Question.** Are students' stress levels higher during midterm week than they are during the 2nd week of classes?

**Hypothesis.** The setup here is as follows:

$$\begin{align*}H_0 &: \mu_{g} = 0 \\H_a &: \mu_{g} > 0\end{align*}$$